### ISSUE TITLE
[Feature] 메인 페이지, 로그인, 회원가입, 유저 검색 퍼블리싱

### ISSUE THREAD

**Issue by ujeans** [modern-agile-team/4term-mini-front#1]
- [x] 검색
- [x] 메인 페이지
- [x] 로그인
- [x] 회원가입

**Comment by ssi02014** [comment]
이슈 등록 할 때 구현하려는 기능 요구사항 좀 더 디테일하게 작성하고, 오른쪽 Assignees, Labels, Projects 이런거 추가해줘유~

**Comment by ssi02014** [comment]
좋은 예시 https://github.com/modern-agile-team/idu-market-next/issues/100
이렇게까지 하라는건 아닌데 지금보다는 디테일하게 ㄲ_ㄲ
