### ISSUE TITLE
[Feature] 메인 페이지, 전체 게시글, 사진 업로드 퍼블리싱

### ISSUE THREAD

**Issue by bang-koon** [modern-agile-team/4term-mini-front#4]
### 메인페이지
- [x]  퍼블리싱
---
### 사진 업로드(모달)
- [x] Navigation.jsx  style분리, 파일 구조 변경
- [x] Navigation Link 연결
- [x] 네비게이션 버튼 이벤트 => 누르면 모달창 나오게
- [x] file 선택 시 포스팅 화면으로

퍼블리싱
- [x] 사진 선택 전 화면(+선택 기능) 
- [x] 사진 선택 후 화면

리팩
- [x] style 분리
- [x]  component 분리

**Comment by ssi02014** [comment]
이슈 등록할 때 구현하려는 기능 요구사항 좀 더 디테일하게 작성하고, 오른쪽 Assignees, Labels, Projects 이런거 추가해줘

**Comment by ssi02014** [comment]
좋은 예시 https://github.com/modern-agile-team/idu-market-next/issues/100
이렇게까지 하라는건 아닌데 지금보다는 디테일하게 ㄲ_ㄲ
