### ISSUE TITLE
[Feature] 유저 프로필 페이지 퍼블리싱

### ISSUE THREAD

**Issue by donkeykong100** [modern-agile-team/4term-mini-front#5]
## 퍼블리싱
/username URL의 유저 프로필 페이지

---
### 유저 프로필 헤더
- [x] 프로필 사진
- [x] 섹션
---
### 바디
- [x] 포스트

**Comment by ssi02014** [comment]
이슈 등록할 때 구현하려는 기능 요구사항 좀 더 디테일하게 작성하고, 오른쪽 Assignees, Labels, Projects 이런거 추가해줘

**Comment by ssi02014** [comment]
좋은 예시 https://github.com/modern-agile-team/idu-market-next/issues/100
이렇게까지 하라는건 아닌데 지금보다는 디테일하게 ㄲ_ㄲ
